# Generated by Django 5.2.5 on 2025-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=200)),
                ('taskDescription', models.TextField()),
                ('creationTime', models.TimeField(auto_now_add=True)),
                ('isDone', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creationTime'],
            },
        ),
    ]
